name: 🎵 Shop Musique
on: [push, workflow_dispatch]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Generate boutique
      uses: appleboy/node-action@v1.0.0
      with:
        version: '20'
        script: |
          console.log('Node OK');
          console.log('Fichiers:', require('fs').readdirSync('.'));
          require('fs').readdirSync('assets')?.forEach(f => console.log('MP3:', f));
          require('./generate-shop.js');
    
    - name: Debug résultat
      run: |
        ls -la index.html || echo "index.html OK"
